
User.create!(name: "brandon", email: "brandon@email.com", password: "password")
User.create!(name: "kate", email: "kate@email.com", password: "password")
User.create!(name: "charlie", email: "charlie@email.com", password: "password")
User.create!(name: "matt", email: "matt@email.com", password: "password")
User.create!(name: "anna", email: "anna@email.com", password: "password")

Song.create!(title: "I Want It That Way", artist: "Backstreet Boys")
Song.create!(title: "Pour Some Sugar On Me", artist: "Def Leppard")
Song.create!(title: "Livin' La Vida Loca", artist: "Ricky Martin")
Song.create!(title: "Wanted Dead or Alive", artist: "Bon Jovi")
Song.create!(title: "Under Pressure", artist: "Queen & David Bowie")

SongVersion.create!(song_id: 1, label: "Sing Sing Karaoke", duration: 251, song_url: "https://www.youtube.com/watch?v=NxilU56kPu0", lyrics: "replace")
SongVersion.create!(song_id: 2, label: "Mozik", duration: 271, song_url: "https://www.youtube.com/watch?v=-4harOr09mk", lyrics: "replace")
SongVersion.create!(song_id: 3, label: "Real Karaoke World", duration: 252, song_url: "https://www.youtube.com/watch?v=36bFVhVBxAA", lyrics: "replace")
SongVersion.create!(song_id: 4, label: "King of Karaoke", duration: 325, song_url: "https://www.youtube.com/watch?v=RHVpwiVOwek", lyrics: "replace")
SongVersion.create!(song_id: 5, label: "Karafun", duration: 240, song_url: "https://www.youtube.com/watch?v=1J_ZNNhbjWs", lyrics: "replace")

Category.create!(title: "'90s Pop Hits", logo_url: "")
Category.create!(title: "Hair Band Rock", logo_url: "")
Category.create!(title: "Boy Bands", logo_url: "")
Category.create!(title: "Latin Crossover", logo_url: "")
Category.create!(title: "'80s Rock'", logo_url: "")

CategorySong.create!(song_id: 1, category_id: 1)
CategorySong.create!(song_id: 1, category_id: 3)
CategorySong.create!(song_id: 2, category_id: 2)
CategorySong.create!(song_id: 3, category_id: 1)
CategorySong.create!(song_id: 3, category_id: 4)
CategorySong.create!(song_id: 4, category_id: 2)
CategorySong.create!(song_id: 2, category_id: 5)
CategorySong.create!(song_id: 4, category_id: 1)
CategorySong.create!(song_id: 5, category_id: 2)

Event.create!(event_name: 1872, event_duration: 120, event_status: "active")
Event.create!(event_name: 1508, event_duration: 90, event_status: "active")

EventUser.create!(user_id: 1, event_id: 1)
EventUser.create!(user_id: 2, event_id: 1)
EventUser.create!(user_id: 3, event_id: 1)
EventUser.create!(user_id: 4, event_id: 1)
EventUser.create!(user_id: 5, event_id: 1)
EventUser.create!(user_id: 1, event_id: 2)
EventUser.create!(user_id: 2, event_id: 2)

EventSong.create!(song_version_id: 1, user_id: 3, event_id: 1)
EventSong.create!(song_version_id: 5, user_id: 4, event_id: 1)
EventSong.create!(song_version_id: 3, user_id: 1, event_id: 1)
EventSong.create!(song_version_id: 2, user_id: 2, event_id: 1)
EventSong.create!(song_version_id: 4, user_id: 5, event_id: 1)
EventSong.create!(song_version_id: 4, user_id: 1, event_id: 2)
EventSong.create!(song_version_id: 3, user_id: 2, event_id: 2)