
User.create!(name: "brandon", email: "brandon@email.com", password: "password")
User.create!(name: "kate", email: "kate@email.com", password: "password")
User.create!(name: "charlie", email: "charlie@email.com", password: "password")
User.create!(name: "matt", email: "matt@email.com", password: "password")
User.create!(name: "anna", email: "anna@email.com", password: "password")
User.create!(name: "jerry", email: "jerry@email.com", password: "password")
User.create!(name: "melanie", email: "melanie@email.com", password: "password")
User.create!(name: "emma", email: "emma@email.com", password: "password")
User.create!(name: "bones", email: "bones@email.com", password: "password")

Song.create!(title: "I Want It That Way", artist: "Backstreet Boys")
Song.create!(title: "Pour Some Sugar On Me", artist: "Def Leppard")
Song.create!(title: "Livin' La Vida Loca", artist: "Ricky Martin")
Song.create!(title: "Wanted Dead or Alive", artist: "Bon Jovi")
Song.create(title: "Under Pressure", artist: "Queen & David Bowie")
Song.create!(title: "Purple Rain", artist: "Prince")
Song.create!(title: "Like A Prayer", artist: "Madonna")
Song.create!(title: "Let's Get It On", artist: "Marvin Gaye")
Song.create!(title: "Private Eyes", artist: "Hall & Oates")
Song.create!(title: "Born to Run", artist: "Bruce Springsteen")
Song.create!(title: "I Wanna Dance With Somebody", artist: "Whitney Houston")
Song.create!(title: "Love Shack", artist: "B-52's")
Song.create!(title: "Forget You", artist: "CeeLo Green")
Song.create!(title: "Since U Been Gone", artist: "Kelly Clarkson")
Song.create!(title: "Stand By Me", artist: "Ben E. King")
Song.create!(title: "Hey Jude", artist: "The Beatles")
Song.create!(title: "Livin' On A Prayer", artist: "Bon Jovi")
Song.create!(title: "You Oughta Know", artist: "Alanis Morissette")
Song.create!(title: "Bohemian Rhapsody", artist: "Queen")
Song.create!(title: "Lean On Me", artist: "Bill Withers")
Song.create!(title: "Don't Go Breaking My Heart", artist: "Elton John & Kiki Dee")
Song.create!(title: "Faith", artist: "George Michael")
Song.create!(title: "The Real Slim Shady", artist: "Eminem")
Song.create!(title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd")
Song.create!(title: "Son of A Preacher Man", artist: "Dusty Springfield")
Song.create!(title: "Let's Stay Together", artist: "Al Green")
Song.create!(title: "(You Gotta) Fight for Your Right (to Party)", artist: "Beastie Boys")
Song.create!(title: "You Make Me Feel Like A Natural Woman", artist: "Aretha Franklin")
Song.create!(title: "I Think We're Alone Now", artist: "Tiffany")
Song.create!(title: "Don't You Want Me", artist: "The Human League")
Song.create!(title: "Space Oddity", artist: "David Bowie")
Song.create!(title: "Tears of a Clown", artist: "Smokey Robinson & the Miracles")
Song.create!(title: "Baby Got Back", artist: "Sir Mix-A-Lot")
Song.create!(title: "Drunk In Love", artist: "Jay-Z and Beyonce")
Song.create!(title: "Say My Name", artist: "Destiny's Child")
Song.create!(title: "Just A Friend", artist: "Biz Markie")
Song.create!(title: "Bitch", artist: "Meredith Brooks")
Song.create!(title: "Africa", artist: "Toto")
Song.create!(title: "Total Eclipse of the Heart", artist: "Bonnie Tyler")
Song.create!(title: "What's Up", artist: "4 Non Blondes")
Song.create!(title: "Semi-Charmed Life", artist: "Third Eye Blind")
Song.create!(title: "Tubthumping", artist: "Chumbawumba")
Song.create!(title: "Summer Nights (from Grease)", artist: "John Travolta & Olivia Newton-John")
Song.create!(title: "I Believe In A Thing Called Love", artist: "The Darkness")
Song.create!(title: "Billie Jean", artist: "Michael Jackson")
Song.create!(title: "Hey Ya", artist: "Outkast")
Song.create!(title: "Rehab", artist: "Amy Winehouse")
Song.create!(title: "Beast of Burden", artist: "Rolling Stones")
Song.create!(title: "What's My Age Again", artist: "Blink 182")
Song.create!(title: "Say It Ain't So", artist: "Weezer")
Song.create!(title: "I Love Rock & Roll", artist: "Joan Jett & the Blackhearts")
Song.create!(title: "Hit Me With Your Best Shot", artist: "Pat Benatar")

SongVersion.create!(song_id: 1, label: "KaraokeOnVEVO", duration: 226, song_url: "LQ3HAwt_ON0", lyrics: "replace")
SongVersion.create!(song_id: 2, label: "Mozik", duration: 271, song_url: "-4harOr09mk", lyrics: "replace")
SongVersion.create!(song_id: 3, label: "Real Karaoke World", duration: 252, song_url: "36bFVhVBxAA", lyrics: "replace")
SongVersion.create!(song_id: 4, label: "King of Karaoke", duration: 325, song_url: "RHVpwiVOwek", lyrics: "replace")
SongVersion.create!(song_id: 5, label: "singsongmusic", duration: 246, song_url: "Up01SjPQrGI", lyrics: "replace")
SongVersion.create!(song_id: 6, label: "Karaoke Rock", duration: 247, song_url: "5I4KtklV7ew", lyrics: "replace")
SongVersion.create!(song_id: 7, label: "Karaoke Phoenix", duration: 334, song_url: "T-SC50aFOVI", lyrics: "replace")
SongVersion.create!(song_id: 8, label: "Let's Sing Karaoke", duration: 259, song_url: "7kIK9f1Yc_8", lyrics: "replace")
SongVersion.create!(song_id: 9, label: "Real World Karaoke", duration: 188, song_url: "Q6s9AWNilUc", lyrics: "replace")
SongVersion.create!(song_id: 10, label: "Let's Sing Karaoke", duration: 277, song_url: "CNxIhOyIsR8", lyrics: "replace")
SongVersion.create!(song_id: 11, label: "Sing King Karaoke", duration: 326, song_url: "03xnpO56kpk", lyrics: "replace")
SongVersion.create!(song_id: 12, label: "Let's Sing Karaoke", duration: 329, song_url: "zm9mcAyTEN8", lyrics: "replace")
SongVersion.create!(song_id: 13, label: "singsongkaraoke", duration: 244, song_url: "Bqk8csVOVP0", lyrics: "replace")
SongVersion.create!(song_id: 14, label: "KaraokeOnVEVO", duration: 205, song_url: "zIc6Ic4e1ss", lyrics: "replace")
SongVersion.create!(song_id: 15, label: "YouSingTheHits", duration: 163, song_url: "9M3wwddDec4", lyrics: "replace")
SongVersion.create!(song_id: 16, label: "YouSingTheHits", duration: 349, song_url: "sKk-3wb9Djg", lyrics: "replace")
SongVersion.create!(song_id: 17, label: "YouSingTheHits", duration: 349, song_url: "sKk-3wb9Djg", lyrics: "replace")
SongVersion.create!(song_id: 18, label: "KaraokeOnVEVO", duration: 266, song_url: "j8OhzlB-JV4", lyrics: "replace")
SongVersion.create!(song_id: 19, label: "Sing Songs Music", duration: 390, song_url: "x5cBBXXFAPQ", lyrics: "replace")
SongVersion.create!(song_id: 20, label: "KaraokeOnVEVO", duration: 226, song_url: "Q4rIFrmWlbc", lyrics: "replace")
SongVersion.create!(song_id: 21, label: "KaraokeOnVEVO", duration: 270, song_url: "tDeLYr8LdUc", lyrics: "replace")
SongVersion.create!(song_id: 22, label: "EasyKaraoke", duration: 196, song_url: "bcAiHIZe_Do", lyrics: "replace")
SongVersion.create!(song_id: 23, label: "Karaoke Version", duration: 291, song_url: "RY3U7nEGs5E", lyrics: "replace")
SongVersion.create!(song_id: 24, label: "KaraokeOnVEVO", duration: 303, song_url: "-odk99MeOfY", lyrics: "replace")
SongVersion.create!(song_id: 25, label: "YouSingTheHits", duration: 173, song_url: "O5YIcwmnAhE", lyrics: "replace")
SongVersion.create!(song_id: 26, label: "KaraokeOnVEVO", duration: 211, song_url: "ZxefBcDt8UE", lyrics: "replace")
SongVersion.create!(song_id: 27, label: "Karaoke Vic", duration: 208, song_url: "2n8VzSDB_24", lyrics: "replace")
SongVersion.create!(song_id: 28, label: "Tracks Planet", duration: 206, song_url: "n3x9MXZfBis", lyrics: "replace")
SongVersion.create!(song_id: 29, label: "Karafun", duration: 231, song_url: "_UPozTSprvY", lyrics: "replace")
SongVersion.create!(song_id: 30, label: "Let's Sing Karaoke", duration: 266, song_url: "CNLfvJhAr2s", lyrics: "replace")
SongVersion.create!(song_id: 31, label: "Mister Tonsy", duration: 317, song_url: "JGoEZ5lPOGk", lyrics: "replace")
SongVersion.create!(song_id: 32, label: "EasyKaraoke", duration: 202, song_url: "eUFW-ElE4Tg", lyrics: "replace")
SongVersion.create!(song_id: 33, label: "Let's Sing Karaoke", duration: 271, song_url: "4xDRa_xn5gA", lyrics: "replace")
SongVersion.create!(song_id: 34, label: "beybaddest", duration: 323, song_url: "8wwc3GmclmI", lyrics: "replace")
SongVersion.create!(song_id: 35, label: "tubemusicvideo1", duration: 283, song_url: "X19vGIqC3kU", lyrics: "replace")
SongVersion.create!(song_id: 36, label: "SBI", duration: 267, song_url: "pa2Eg5ruXqA", lyrics: "replace")
SongVersion.create!(song_id: 37, label: "Let's Sing!", duration: 252, song_url: "p5o7iq5BhtM", lyrics: "replace")
SongVersion.create!(song_id: 38, label: "King of Karaoke", duration: 324, song_url: "bRtadt24Geo", lyrics: "replace")
SongVersion.create!(song_id: 39, label: "KaraokeOnVEVO", duration: 341, song_url: "d1axakrbjGc", lyrics: "replace")
SongVersion.create!(song_id: 40, label: "Let's Sing Karaoke", duration: 267, song_url: "58Zv6E4cqNs", lyrics: "replace")
SongVersion.create!(song_id: 41, label: "Skill Express Karaoke", duration: 278, song_url: "8LUxZfQI89c", lyrics: "replace")
SongVersion.create!(song_id: 42, label: "Karafun", duration: 248, song_url: "CypKX2yHpLg", lyrics: "replace")
SongVersion.create!(song_id: 43, label: "Karafun", duration: 224, song_url: "tpQM4xLdUig", lyrics: "replace")
SongVersion.create!(song_id: 44, label: "EasyKaraoke", duration: 219, song_url: "X92erN-RVYg", lyrics: "replace")
SongVersion.create!(song_id: 45, label: "Sing Sing Karaoke", duration: 336, song_url: "eXqBhDAlVCc", lyrics: "replace")
SongVersion.create!(song_id: 46, label: "Sing Sing Karaoke", duration: 285, song_url: "l9Ftxu38r0w", lyrics: "replace")
SongVersion.create!(song_id: 47, label: "The Karaoke Channel", duration: 230, song_url: "w42pSGRICag", lyrics: "replace")
SongVersion.create!(song_id: 48, label: "Karafun", duration: 276, song_url: "uV-nI9Tg0X4", lyrics: "replace")
SongVersion.create!(song_id: 49, label: "Karafun", duration: 156, song_url: "pagHlXLIJw0", lyrics: "replace")
SongVersion.create!(song_id: 50, label: "King of Karaoke", duration: 288, song_url: "E8AWuCTOk5I", lyrics: "replace")
SongVersion.create!(song_id: 51, label: "Good Karaoke Songs", duration: 190, song_url: "XBYH8Sycu0g", lyrics: "replace")
SongVersion.create!(song_id: 52, label: "The Karaoke Channel", duration: 171, song_url: "YscRzIhuDLw", lyrics: "replace")


Category.create!(title: "Totally '80s", logo_url: "")
Category.create!(title: "Power Ballads", logo_url: "")
Category.create!(title: "Songs You Forgot On Purpose", logo_url: "")
Category.create!(title: "One-Hit Wonders", logo_url: "")
Category.create!(title: "Reality Bites", logo_url: "")
Category.create!(title: "Last Call Songs", logo_url: "")

# CategorySong.create!(song_id: 1, category_id: 1)
# CategorySong.create!(song_id: 1, category_id: 3)
# CategorySong.create!(song_id: 2, category_id: 2)
# CategorySong.create!(song_id: 3, category_id: 1)
# CategorySong.create!(song_id: 3, category_id: 4)
# CategorySong.create!(song_id: 4, category_id: 2)
# CategorySong.create!(song_id: 2, category_id: 5)
# CategorySong.create!(song_id: 4, category_id: 1)
# CategorySong.create!(song_id: 5, category_id: 2)

Event.create!(event_duration: 120, event_status: "active")
Event.create!(event_duration: 90, event_status: "active")

# EventUser.create!(user_id: 1, event_id: 1)
# EventUser.create!(user_id: 1, event_id: 1)
# EventUser.create!(user_id: 2, event_id: 1)
# EventUser.create!(user_id: 3, event_id: 1)
# EventUser.create!(user_id: 4, event_id: 1)
# EventUser.create!(user_id: 5, event_id: 1)
# EventUser.create!(user_id: 1, event_id: 2)
# EventUser.create!(user_id: 2, event_id: 2)

# EventSong.create!(song_version_id: 1, user_id: 3, event_id: 1)
# EventSong.create!(song_version_id: 5, user_id: 4, event_id: 1)
# EventSong.create!(song_version_id: 3, user_id: 1, event_id: 1)
# EventSong.create!(song_version_id: 2, user_id: 2, event_id: 1)
# EventSong.create!(song_version_id: 4, user_id: 5, event_id: 1)
# EventSong.create!(song_version_id: 4, user_id: 1, event_id: 2)
# EventSong.create!(song_version_id: 3, user_id: 2, event_id: 2)