
User.create!(name: "brandon", email: "brandon@email.com", password: "password")
User.create!(name: "kate", email: "kate@email.com", password: "password")
User.create!(name: "charlie", email: "charlie@email.com", password: "password")
User.create!(name: "matt", email: "matt@email.com", password: "password")
User.create!(name: "anna", email: "anna@email.com", password: "password")
User.create!(name: "jerry", email: "jerry@email.com", password: "password")
User.create!(name: "melanie", email: "melanie@email.com", password: "password")
User.create!(name: "emma", email: "emma@email.com", password: "password")
User.create!(name: "bones", email: "bones@email.com", password: "password")

Song.create!(title: "I Want It That Way", artist: "Backstreet Boys")
Song.create!(title: "Pour Some Sugar On Me", artist: "Def Leppard")
Song.create!(title: "Livin' La Vida Loca", artist: "Ricky Martin")
Song.create!(title: "Wanted Dead or Alive", artist: "Bon Jovi")
Song.create(title: "Under Pressure", artist: "Queen & David Bowie")
Song.create!(title: "Purple Rain", artist: "Prince")
Song.create!(title: "Like A Prayer", artist: "Madonna")
Song.create!(title: "Let's Get It On", artist: "Marvin Gaye")
Song.create!(title: "Private Eyes", artist: "Hall & Oates")
Song.create!(title: "Born to Run", artist: "Bruce Springsteen")
Song.create!(title: "I Wanna Dance With Somebody", artist: "Whitney Houston")
Song.create!(title: "Love Shack", artist: "B-52's")
Song.create!(title: "Forget You", artist: "CeeLo Green")
Song.create!(title: "Since U Been Gone", artist: "Kelly Clarkson")
Song.create!(title: "Stand By Me", artist: "Ben E. King")
Song.create!(title: "Hey Jude", artist: "The Beatles")
Song.create!(title: "Livin' On A Prayer", artist: "Bon Jovi")
Song.create!(title: "You Oughta Know", artist: "Alanis Morissette")
Song.create!(title: "Bohemian Rhapsody", artist: "Queen")
Song.create!(title: "Lean On Me", artist: "Bill Withers")
Song.create!(title: "Don't Go Breaking My Heart", artist: "Elton John & Kiki Dee")
Song.create!(title: "Faith", artist: "George Michael")
Song.create!(title: "The Real Slim Shady", artist: "Eminem")
Song.create!(title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd")
Song.create!(title: "Son of A Preacher Man", artist: "Dusty Springfield")
Song.create!(title: "Let's Stay Together", artist: "Al Green")
Song.create!(title: "(You Gotta) Fight for Your Right (to Party)", artist: "Beastie Boys")
Song.create!(title: "You Make Me Feel Like A Natural Woman", artist: "Aretha Franklin")
Song.create!(title: "I Think We're Alone Now", artist: "Tiffany")
Song.create!(title: "Don't You Want Me", artist: "The Human League")
Song.create!(title: "Space Oddity", artist: "David Bowie")
Song.create!(title: "Tears of a Clown", artist: "Smokey Robinson & the Miracles")
Song.create!(title: "Baby Got Back", artist: "Sir Mix-A-Lot")
Song.create!(title: "Drunk In Love", artist: "Jay-Z and Beyonce")
Song.create!(title: "Say My Name", artist: "Destiny's Child")
Song.create!(title: "Just A Friend", artist: "Biz Markie")
Song.create!(title: "Bitch", artist: "Meredith Brooks")
Song.create!(title: "Africa", artist: "Toto")
Song.create!(title: "Total Eclipse of the Heart", artist: "Bonnie Tyler")
Song.create!(title: "What's Up", artist: "4 Non Blondes")
Song.create!(title: "Semi-Charmed Life", artist: "Third Eye Blind")
Song.create!(title: "Tubthumping", artist: "Chumbawumba")
Song.create!(title: "Summer Nights (from Grease)", artist: "John Travolta & Olivia Newton-John")
Song.create!(title: "I Believe In A Thing Called Love", artist: "The Darkness")
Song.create!(title: "Billie Jean", artist: "Michael Jackson")
Song.create!(title: "Hey Ya", artist: "Outkast")
Song.create!(title: "Rehab", artist: "Amy Winehouse")
Song.create!(title: "Beast of Burden", artist: "Rolling Stones")
Song.create!(title: "What's My Age Again", artist: "Blink 182")
Song.create!(title: "Say It Ain't So", artist: "Weezer")
Song.create!(title: "I Love Rock & Roll", artist: "Joan Jett & the Blackhearts")
Song.create!(title: "Hit Me With Your Best Shot", artist: "Pat Benatar")

SongVersion.create!(song_id: 1, label: "Sing Sing Karaoke", duration: 251, song_url: "https://www.youtube.com/embed/NxilU56kPu0?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 2, label: "Mozik", duration: 271, song_url: "https://www.youtube.com/embed/-4harOr09mk?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 3, label: "Real Karaoke World", duration: 252, song_url: "https://www.youtube.com/embed/36bFVhVBxAA?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 4, label: "King of Karaoke", duration: 325, song_url: "https://www.youtube.com/embed/RHVpwiVOwek?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 5, label: "Karaoke Theory", duration: 240, song_url: "https://www.youtube.com/embed/1J_ZNNhbjWs?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 6, label: "Karaoke Rock", duration: 247, song_url: "https://www.youtube.com/embed/5I4KtklV7ew?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 7, label: "Karaoke Phoenix", duration: 334, song_url: "https://www.youtube.com/embed/T-SC50aFOVI?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 8, label: "Let's Sing Karaoke", duration: 259, song_url: "https://www.youtube.com/embed/7kIK9f1Yc_8?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 9, label: "Real World Karaoke", duration: 188, song_url: "https://www.youtube.com/embed/Q6s9AWNilUc?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 10, label: "Karafun", duration: 272, song_url: "https://www.youtube.com/embed/BkITLsJBHPg?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 11, label: "Sing King Karaoke", duration: 326, song_url: "https://www.youtube.com/embed/st-yPBxRVPM?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 12, label: "Let's Sing Karaoke", duration: 329, song_url: "https://www.youtube.com/embed/zm9mcAyTEN8?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 13, label: "Sing King Karaoke", duration: 253, song_url: "https://www.youtube.com/embed/l-hN9wzbPJE?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 14, label: "Sing King Karaoke", duration: 223, song_url: "https://www.youtube.com/embed/B8S0l--gHgA?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 15, label: "YouSingTheHits", duration: 163, song_url: "https://www.youtube.com/embed/9M3wwddDec4?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 16, label: "Karafun", duration: 309, song_url: "https://www.youtube.com/embed/yOt-umPG_X0?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 17, label: "Sound Choice", duration: 267, song_url: "https://www.youtube.com/embed/e-OPwNVFkq4?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 18, label: "Karafun", duration: 263, song_url: "https://www.youtube.com/embed/0BKshfVAS4Q?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 19, label: "Sing Songs Music", duration: 390, song_url: "https://www.youtube.com/embed/x5cBBXXFAPQ?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 20, label: "The Karaoke Channel", duration: 245, song_url: "https://www.youtube.com/embed/juBHK0RRG2Y?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 21, label: "Karafun", duration: 277, song_url: "https://www.youtube.com/embed/OPmFTDWoW60?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 22, label: "Karafun", duration: 194, song_url: "https://www.youtube.com/embed/qOM3t6T6owI?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 23, label: "Karaoke Version", duration: 291, song_url: "https://www.youtube.com/embed/RY3U7nEGs5E?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 24, label: "Karafun", duration: 310, song_url: "https://www.youtube.com/embed/NzGFmfi34pQ?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 25, label: "YouSingTheHits", duration: 173, song_url: "https://www.youtube.com/embed/O5YIcwmnAhE?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 26, label: "Karafun", duration: 206, song_url: "https://www.youtube.com/embed/wYJurhuvQy4?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 27, label: "Karafun", duration: 216, song_url: "https://www.youtube.com/embed/5ET4isg2eYM?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 28, label: "Tracks Planet", duration: 206, song_url: "https://www.youtube.com/embed/n3x9MXZfBis?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 29, label: "Karafun", duration: 231, song_url: "https://www.youtube.com/embed/_UPozTSprvY?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 30, label: "Let's Sing Karaoke", duration: 266, song_url: "https://www.youtube.com/embed/CNLfvJhAr2s?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 31, label: "Karafun", duration: 309, song_url: "https://www.youtube.com/embed/UJa8azw5Cg8?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 32, label: "Karafun", duration: 199, song_url: "https://www.youtube.com/embed/XPWs795OAmU?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 33, label: "Karafun", duration: 273, song_url: "https://www.youtube.com/embed/_3LRjzgMxcw?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 34, label: "Sing King Karaoke", duration: 346, song_url: "https://www.youtube.com/embed/ESjYIzQYtIo?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 35, label: "Karafun", duration: 281, song_url: "https://www.youtube.com/embed/4I4Q-3zUqdI?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 36, label: "Skill Express", duration: 271, song_url: "https://www.youtube.com/embed/V41g-eaZ7mQ?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 37, label: "Karafun", duration: 261, song_url: "https://www.youtube.com/embed/o9E_qeRN3eU?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 38, label: "King of Karaoke", duration: 324, song_url: "https://www.youtube.com/embed/bRtadt24Geo?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 39, label: "The Karaoke Channel", duration: 336, song_url: "https://www.youtube.com/embed/pnJRZU4oAi8?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 40, label: "Let's Sing Karaoke", duration: 267, song_url: "https://www.youtube.com/embed/58Zv6E4cqNs?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 41, label: "Karafun", duration: 226, song_url: "https://www.youtube.com/embed/ObP2xHyzdJ4?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 42, label: "Karafun", duration: 248, song_url: "https://www.youtube.com/embed/CypKX2yHpLg?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 43, label: "Karafun", duration: 224, song_url: "https://www.youtube.com/embed/tpQM4xLdUig?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 44, label: "EasyKaraoke", duration: 219, song_url: "https://www.youtube.com/embed/X92erN-RVYg?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 45, label: "Sing Sing Karaoke", duration: 336, song_url: "https://www.youtube.com/embed/eXqBhDAlVCc?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 46, label: "Sing Sing Karaoke", duration: 285, song_url: "https://www.youtube.com/embed/l9Ftxu38r0w?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 47, label: "The Karaoke Channel", duration: 230, song_url: "https://www.youtube.com/embed/w42pSGRICag?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 48, label: "Karafun", duration: 276, song_url: "https://www.youtube.com/embed/uV-nI9Tg0X4?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 49, label: "Karafun", duration: 156, song_url: "https://www.youtube.com/embed/pagHlXLIJw0?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 50, label: "King of Karaoke", duration: 288, song_url: "https://www.youtube.com/embed/E8AWuCTOk5I?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 51, label: "Good Karaoke Songs", duration: 190, song_url: "https://www.youtube.com/embed/XBYH8Sycu0g?autoplay=1", lyrics: "replace")
SongVersion.create!(song_id: 52, label: "The Karaoke Channel", duration: 171, song_url: "https://www.youtube.com/embed/YscRzIhuDLw?autoplay=1", lyrics: "replace")


Category.create!(title: "'90s Pop Hits", logo_url: "")
Category.create!(title: "Hair Band Rock", logo_url: "")
Category.create!(title: "Boy Bands", logo_url: "")
Category.create!(title: "Latin Crossover", logo_url: "")
Category.create!(title: "'80s Rock'", logo_url: "")

CategorySong.create!(song_id: 1, category_id: 1)
CategorySong.create!(song_id: 1, category_id: 3)
CategorySong.create!(song_id: 2, category_id: 2)
CategorySong.create!(song_id: 3, category_id: 1)
CategorySong.create!(song_id: 3, category_id: 4)
CategorySong.create!(song_id: 4, category_id: 2)
CategorySong.create!(song_id: 2, category_id: 5)
CategorySong.create!(song_id: 4, category_id: 1)
CategorySong.create!(song_id: 5, category_id: 2)

Event.create!(event_duration: 120, event_status: "active")
Event.create!(event_duration: 90, event_status: "active")

# EventUser.create!(user_id: 1, event_id: 1)
# EventUser.create!(user_id: 1, event_id: 1)
# EventUser.create!(user_id: 2, event_id: 1)
# EventUser.create!(user_id: 3, event_id: 1)
# EventUser.create!(user_id: 4, event_id: 1)
# EventUser.create!(user_id: 5, event_id: 1)
# EventUser.create!(user_id: 1, event_id: 2)
# EventUser.create!(user_id: 2, event_id: 2)

# EventSong.create!(song_version_id: 1, user_id: 3, event_id: 1)
# EventSong.create!(song_version_id: 5, user_id: 4, event_id: 1)
# EventSong.create!(song_version_id: 3, user_id: 1, event_id: 1)
# EventSong.create!(song_version_id: 2, user_id: 2, event_id: 1)
# EventSong.create!(song_version_id: 4, user_id: 5, event_id: 1)
# EventSong.create!(song_version_id: 4, user_id: 1, event_id: 2)
# EventSong.create!(song_version_id: 3, user_id: 2, event_id: 2)